config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get   'inquiry'         => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'

  get "search" => "searches#search"

  devise_for :users

  root 'homes#top'
  get 'about' => 'homes#about'


  resources :shops, only: [:new,:index,:show,:edit,:create,:destroy,:update]do
    resource :favorites, only: [:create, :destroy]
    resources :shop_comments, only: [:create, :destroy]
  end

  resources :ranks, only: [:index]

  resources :users, only: [:index,:show,:edit,:update] do
    resources :favorites, only: [:index]
  end
  #退会確認画面
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  #論理削除用のルーティング
  patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'

  resources :notifications, only: [:index]


end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :shop_comments, dependent: :destroy

  has_many :notifications, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :genre, presence: true
  validates :address, presence: true
  validates :brand, presence: true
  validates :description, presence: true,length:{maximum:200}



  def shop_image
    image.attached? ? image : 'no_image.jpg'
  end


  def favorited_by?(user)

    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @shop = Shop.where("name LIKE? OR address like? OR brand like?", "#{word}", "#{word}", "#{word}" )
    elsif search == "partial_match"
      @shop = Shop.where("name LIKE? OR address like? OR brand like?", "%#{word}%", "%#{word}%", "%#{word}%" )
    else
      @shop = Shop.all
    end
  end


  #Google map表示機能
  geocoded_by :address
  after_validation :geocode, if: :address_changed?


  #通知機能
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      shop_id: id,
      visited_id: user_id,
      action: "favorite"
    )
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_user, shop_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = ShopComment.select(:user_id).where(shop_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, shop_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, shop_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, shop_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      shop_id: id,
      shop_comment_id: shop_comment_id,
      visited_id: visited_id,
      action: 'shop_comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!



  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.user_id = current_user.id
    if @shop.save
      redirect_to shop_path(@shop), notice: "投稿が成功しました！"
    else
      render 'new'
    end
  end

  def index
    @shops = Shop.all.page(params[:page]).per(9)
  end

  def show
    @shop = Shop.find(params[:id])
    @user = @shop.user
    @shop_comment = ShopComment.new
  end

  def edit
    @shop = Shop.find(params[:id])
    if @shop.user ==current_user
      render "edit"
    else
      redirect_to shops_path
    end
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to shop_path(@shop), notice: "更新が成功しました！"
    else
      render "edit"
    end
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    redirect_to shops_path
  end


  private

  def shop_params
    params.require(:shop).permit(:name, :address, :genre, :brand, :rate, :description, :latitude, :longitude, :image)
  end


end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_static_rate.html.erb
<div id="rate_<%= shop.id %>" class="form-group"></div>
<script>
$(document).on('turbolinks:load', function() {
  $('#rate_<%= shop.id %>').empty();
  $('#rate_<%= shop.id %>').raty({
    size: 20,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= shop.rate %>,
  });
});
</script>

app/views/shops/edit.html.erb
<%= render 'layouts/errors', obj: @shop %>
<div class="container">
  <div class="row mt-3">
    <div class="col-3">
      <h2 class="title-text offset-2">投稿編集</h2>
    </div>
    <%= form_with model: @shop, url: shop_path do |f| %>
      <div class="row d-flex justify-content-start mt-3">
        <div class="col-2 mt-2">
          <%= f.label :ショップ画像, class: 'mt-1' %>
        </div>
        <div class="col-4 mt-2">
          <%= f.file_field :image_id, class: "form-control-file user_image", accept: 'image/*' %>
        </div>
        <div class="col-6"></div>

        <div class="col-2 mt-2">
          <%= f.label :ショップ名, class: 'mt-1' %>
        </div>
        <div class="col-4 mt-2">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="col-6"></div>

        <div class="col-2 mt-2">
          <%= f.label :ショップのジャンル, class: 'mt-1' %>
        </div>
        <div class="col-4 mt-2">
          <%= f.select :genre, ['旗艦店', 'セレクトショップ', '古着屋', 'その他'], {include_blank: 'ジャンル選択ボックス'}, class: 'sample' %>
        </div>
        <div class="col-6"></div>

        <div class="col-2 mt-2">
          <%= f.label :ショップの住所, class: 'mt-1' %>
        </div>
        <div class="col-4 mt-2">
          <%= f.text_field :address, class: 'form-control' %>
        </div>
        <div class="col-6"></div>

        <div class="col-2 mt-2">
          <%= f.label :ショップの取扱ブランド, class: 'mt-1' %>
        </div>
        <div class="col-4 mt-2">
          <%= f.text_area :brand, class: 'form-control' %>
        </div>
        <div class="col-6"></div>

        <div class="col-2 mt-2">
          <%= f.label :star,'評価 ', class: 'mt-1' %>
        </div>
        <div class="col-9 mt-2 " id="star">
         <%= f.hidden_field :star, id: :review_star, class:'form-control' %>
        </div>

        <script>
        $(document).on('turbolinks:load', function() {
          $('#star').empty();
          $('#star').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'shop[rate]',
            half: true,
          });
        })
        </script>

        <div class="col-2 mt-2">
          <%= f.label :口コミ内容, class: 'mt-1' %>
        </div>
        <div class="col-4 mt-2">
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <div class="col-6"></div>

        <div class="col-2"></div>
        <div class="col-4 mt-2">
          <%= f.submit "変更を保存", class: 'btn btn-sm btn-success mt-3' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shops/index.html.erb
<%= render 'searches/search' %>
<div class="container my-5">
  <h2 class="title-text">ショップ一覧</h2>
  <%= link_to ranks_path, class: 'text-dark' do %>
    <p>お気に入り登録数ランキング</p>
  <% end %>
  <div class="row">
    <% @shops.each do |shop| %>
  		<div class="col-lg-4 col-md-5 mb-4">
  		  <%= link_to shop_path(shop) do %>
          <%= image_tag shop.shop_image, size: "200x150" %>
        <% end %>
        <table class="table-box">
          <tr >
            <th>ショップ</th>
            <td><%= shop.name %></td>
          </tr>
          <tr>
            <th>ジャンル</th>
            <td><%= shop.genre %></td>
          </tr>
          <tr>
            <th>ブランド</th>
            <td><%= shop.brand %></td>
          </tr>
          <tr>
            <th>住所</th>
            <th><%= shop.address %></th>
          </tr>
          <tr>
            <th>評価</th>
            <td><%= render "static_rate", shop: shop %></td>
          </tr>
          <tr>
            <th>お気に入り</th>
            <td id="shop_<%= shop.id %>" class="favorite-btn">
              <%= render "favorites/favorite-btn", shop: shop %>
            </td>
          </tr>
        </table>
      </div>
    <% end %>
    <div class="paginate">
      <%= paginate @shops %>
    </div>
  </div>
</div>

app/views/shops/new.html.erb
<%= render 'layouts/errors', obj: @shop %>
<div class="container">
  <div class="row mt-3">
    <div class="col-3">
      <h2 class="title-text offset-2">新規投稿</h2>
    </div>
    <%= form_with model: @shop, url: shops_path do |f| %>
      <div class="row d-flex justify-content-start mt-3">
        <div class="col-2 mt-2">
          <%= f.label :ショップ画像, class: 'mt-1' %>
        </div>
        <div class="col-4 mt-2">
          <%= f.file_field :image, class: "form-control-file user_image", accept: 'image/*' %>
        </div>
        <div class="col-6"></div>

        <div class="col-2 mt-2">
          <%= f.label :ショップ名, class: 'mt-1' %>
        </div>
        <div class="col-4 mt-2">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="col-6"></div>

        <div class="col-2 mt-2">
          <%= f.label :ショップのジャンル, class: 'mt-1' %>
        </div>
        <div class="col-4 mt-2">
          <%= f.select :genre, ['旗艦店', 'セレクトショップ', '古着屋', 'その他'], {include_blank: 'ジャンル選択ボックス'}, class: 'sample' %>
        </div>
        <div class="col-6"></div>

        <div class="col-2 mt-2">
          <%= f.label :ショップの住所, class: 'mt-1' %>
        </div>
        <div class="col-4 mt-2">
          <%= f.text_field :address, class: 'form-control' %>
        </div>
        <div class="col-6"></div>

        <div class="col-2 mt-2">
          <%= f.label :ショップの取扱ブランド（購入ブランド）, class: 'mt-1' %>
        </div>
        <div class="col-4 mt-2">
          <%= f.text_area :brand, class: 'form-control' %>
        </div>
        <div class="col-6"></div>

        <div class="col-2 mt-2">
          <%= f.label :star,'評価 ', class: 'mt-1' %>
        </div>
       <div class="col-9 mt-2 " id="star">
         <%= f.hidden_field :star, id: :review_star, class:'form-control' %>
        </div>

        <script>
        $(document).on('turbolinks:load', function() {
          $('#star').empty();
          $('#star').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'shop[rate]',
            half: true,
          });
        })
        </script>

        <div class="col-2 mt-2">
          <%= f.label :口コミ内容, class: 'mt-1' %>
        </div>
        <div class="col-4 mt-2">
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <div class="col-6"></div>

        <div class="col-2"></div>
        <div class="col-4 mt-2">
          <%= f.submit "新規投稿", class: 'btn btn-sm btn-success mt-3' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shops/show.html.erb
<div class="container my-5">
  <h2 class="title-text">ショップ詳細</h2>
  <div class="row">
    <div class="col-md-8">
      <table class="table table-bordered border-dark">
        <tr class="brown-border">
          <td class="table-secondary">投稿者</td>
          <td>
            <%= link_to user_path(@user), class: "link" do %>
              <%= @user.nickname %>
            <% end %>
          </td>
        </tr>
        <tr class="brown-border">
          <td class="table-secondary">ショップ画像</td>
          <td><%= image_tag @shop.shop_image, size:'200x150' %></td>
        </tr>
        <tr class="brown-border">
          <td class="table-secondary">ショップ名</td>
          <td><%= @shop.name %></td>
        </tr>
        <tr class="brown-border">
          <td class="table-secondary">ショップのジャンル</td>
          <td><%= @shop.genre %></td>
        </tr>
        <tr class="brown-border">
          <td class="table-secondary">取扱or購入ブランド</td>
          <td><%= @shop.brand %></td>
        </tr>
        <tr class="brown-border">
          <td class="table-secondary">ショップの住所</td>
          <td>
            <%= @shop.address %><br>
            <script type="text/javascript">
              function initMap() {
            // latitude,longitudeから位置を特定
                var test ={lat: <%= @shop.latitude %>, lng: <%= @shop.longitude %>};
                var map = new google.maps.Map(document.getElementById('map'), {
                          zoom: 15,
                          center: test
                          });
                var transitLayer = new google.maps.TransitLayer();
                transitLayer.setMap(map);

                var contentString = '住所：<%= @shop.address %>';
                var infowindow = new google.maps.InfoWindow({
                  content: contentString
                });

            // Map上の指定した位置にピンを挿して表示する
                var marker = new google.maps.Marker({
                              position:test,
                              map: map,
                              title: contentString
                             });

                 marker.addListener('click', function() {
                   infowindow.open(map, marker);
                 });
              }
            </script>
            <script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
            </script>
            <!--表示するmapのcss-->
            <style type="text/css">
              #map { height: 200px;
                     width: 90%;}
            </style>

            <!--mapの表示-->
            <div id="map"></div>
          </td>
        </tr>
        <tr class="brown-border">
          <td class="table-secondary">お気に入り</td>
          <td id="shop_<%= @shop.id %>" class="favorite-btn">
            <%= render "favorites/favorite-btn", shop: @shop %>
          </td>
        </tr>
        <tr class="brown-border">
          <td class="table-secondary">コメント件数</td>
          <td class="comments-count">
            <%= @shop.shop_comments.count %>
          </td>
        </tr>
      </table>

      <table class="table table-bordered border-dark">
        <tr class="brown-border">
          <td class="table-secondary">評価</td>
          <td><%= render "static_rate", shop: @shop %></td>
        <tr>
        <tr class="brown-border">
          <td class="table-secondary">口コミ内容</td>
          <td><%= @shop.description %></td>
        <tr>
      </table>
      <div>
        <% if @shop.user == current_user %>
          <%= link_to '投稿を編集する', edit_shop_path(@shop), class: "btn btn-sm btn-success edit_shop_#{@shop.id}" %>
          <%= link_to '投稿を削除する', @shop, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_shop_#{@shop.id}"%>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <table class='shop_comments'>
        <%= render 'shop_comments/index', shop: @shop %>
      </table>
      <%= form_with model:[@shop, @shop_comment], local: false do |f| %>
        <%= f.text_area :comment, rows:'5', placeholder: "コメントを入力して下さい", class: "form-control" %>
        <%= f.submit "  送信  " %>
      <% end %>
    </div>
  </div>
</div>