config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get   'inquiry'         => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'

  get "search" => "searches#search"

  devise_for :users

  root 'homes#top'
  get 'about' => 'homes#about'


  resources :shops, only: [:new,:index,:show,:edit,:create,:destroy,:update]do
    resource :favorites, only: [:create, :destroy]
    resources :shop_comments, only: [:create, :destroy]
  end

  resources :ranks, only: [:index]

  resources :users, only: [:index,:show,:edit,:update] do
    resources :favorites, only: [:index]
  end
  #退会確認画面
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  #論理削除用のルーティング
  patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'

  resources :notifications, only: [:index]


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shops, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_shops, through: :favorites, source: :shop
  has_many :shop_comments, dependent: :destroy

  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy


  has_one_attached :profile_image

  validates :name, presence: true
  validates :nickname, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, presence: true, length: {maximum: 50}


  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end


  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:is_deleted, :name, :nickname, :introduction, :email, :password])
  end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :customer_state, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  protected

  #会員の論理削除のための記述。退会後は、同じアカウントでは利用できない。
  def reject_user
    @user = User.find_by(name: params[:user][:name])
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == false)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]


  def show
    @user = User.find(params[:id])
    @shops = @user.shops
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "更新が成功しました！"
    else
      render "edit"
    end
  end

  def unsubscribe
  end


  def withdraw
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:nickname, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render 'layouts/errors', obj: @user %>
<div class="container">
  <div class="row mt-3">
    <div class="col-3">
      <h2 class="title-text offset-2">プロフィール編集</h2>
    </div>
  </div>
  <%= form_with model:@user, local:true do |f| %>
    <div class="row d-flex justify-content-start mt-3">
      
      <div class="col-2 mt-2">
        <%= f.label :プロフィール画像, class: 'mt-1' %>
      </div>
      <div class="col-4 mt-2">
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="col-6"></div>

      <div class="col-2 mt-2">
        <%= f.label :ニックネーム, class: 'mt-1' %>
      </div>
      <div class="col-4 mt-2">
        <%= f.text_field :nickname, class: "form-control" %>
      </div>
      <div class="col-6"></div>

      <div class="col-2 mt-2">
        <%= f.label :メールアドレス, class: 'mt-1' %>
      </div>
      <div class="col-4 mt-2">
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="col-6"></div>

      <div class="col-2 mt-2">
        <%= f.label :自己紹介文, class: 'mt-1' %>
      </div>
      <div class="col-4 mt-2">
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="col-6"></div>

      <div class="col-2"></div>
      <div class="col-4 mt-2">
        <div class="d-flex bd-highlight mb-3">
          <div class="bd-highlight"><%= f.submit "編集内容を保存する", class: "btn btn-sm btn-success" %></div>
          <div class="ms-auto bd-highlight"><%= link_to "退会する", unsubscribe_path(@user), class: "btn btn-sm btn-danger" %></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <table class="side-table">
        <tr>
          <%= image_tag @user.get_profile_image, size:'100x100' %>
        </tr>
        <tr>
          <th>ニックネーム</th>
          <th><%= @user.nickname %></th>
        </tr>
        <tr>
          <th>自己紹介</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>
      <% if @user == current_user %>
        <%= link_to edit_user_path(@user), class: "text-dark" do %>
          <i class="fas fa-user-cog"></i>プロフィール編集<br>
        <% end %>
        <div>
          <%= link_to user_favorites_path(@user), class: "text-dark" do %>
            <i class="fas fa-star"></i>お気に入り一覧
          <% end %>
        </div>
        <div>
          <% if unchecked_notifications.any? %>
            <i class="fas fa-circle" style="color: gold;"></i>
          <% end %>
          <%= link_to notifications_path, class: "text-dark" do %>
            <i class="fas fa-bell"></i>通知一覧
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="col-9">
      <div class="title-text">
        <h2><%= @user.nickname %>さんの投稿一覧</h2>
      </div>
      <div>
        <% if @user == current_user %>
          <%= link_to new_shop_path, class: "btn btn-outline-success" do %>
            新規投稿<i class="fas fa-plus"></i>
          <% end %>
        <% end %>
      </div>
      <div class="mt-3">
        <% @shops.each do |shop| %>
          <div class="user-shops">
            <div>
              <%= link_to shop_path(shop) do %>
                <%= image_tag shop.shop_image, size: "200x150" %>
              <% end %>
            </div>
            <div><%= shop.name %></div>
            <div><%= shop.brand %></div>
            <div><%= render "shops/static_rate", shop: shop %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class="container my-5 text-center">
  <div class="row">
    <div class="offset-1 col-6 m-auto">
    <h1 class="red-border px-3">本当に退会しますか？</h1>
      <div class="my-5">
        <p>退会すると、会員登録情報や</P>
        <p>これまでの投稿やお気に入りが閲覧できなくなります。</p>
        <p>退会する場合は、「退会する」をクリックしてください。</p>
      </div>
      <div class="m-auto">
        <%= link_to "退会しない", user_path(current_user), class:"btn btn-primary" %>
        <%= link_to "退会する", withdraw_path, method: :patch, data: {confirm: "本当に退会してもよろしいですか？"}, class:"btn btn-danger" %>
      </div>
      <div>
        © 2022 GitHub, Inc.Terms
      </div>
    </div>
  </div>
</div>