config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get   'inquiry'         => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'

  get "search" => "searches#search"

  devise_for :users

  root 'homes#top'
  get 'about' => 'homes#about'


  resources :shops, only: [:new,:index,:show,:edit,:create,:destroy,:update]do
    resource :favorites, only: [:create, :destroy]
    resources :shop_comments, only: [:create, :destroy]
  end

  resources :ranks, only: [:index]

  resources :users, only: [:index,:show,:edit,:update] do
    resources :favorites, only: [:index]
  end
  #退会確認画面
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  #論理削除用のルーティング
  patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'

  resources :notifications, only: [:index]


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    @shops = Shop.looks(params[:search], params[:word])
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<div class="search">
  <h6 class="search-text">ショップ検索</h6>
  <div class="search-form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word, placeholder:"ショップ名・ブランド・住所を検索", size: "40x40" %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-sm btn-outline-success" %>
    <% end %>
  </div>
</div>

app/views/searches/search.html.erb
<div class="container my-5">
  <h2 class="title-text">検索結果一覧</h2>
  <div class="row">
    <% @shops.each do |shop| %>
  		<div class="col-md-3">
  		  <%= link_to shop_path(shop) do %>
          <%= image_tag shop.shop_image, size: "200x150" %>
        <% end %>
      </div>
      <div class="col-md-9">
        <table class="table-box">
          <tr>
            <th>ショップ</th>
            <td><%= shop.name %></td>
          </tr>
          <tr>
            <th>ジャンル</th>
            <td><%= shop.genre %></td>
          </tr>
          <tr>
            <th>取扱ブランド</th>
            <td><%= shop.brand %></td>
          </tr>
          <tr>
            <th>住所</th>
            <th><%= shop.address %></th>
          </tr>
          <tr>
            <th>評価</th>
            <td><%= render "shops/static_rate", shop: shop %></td>
          </tr>
          <tr>
            <th>お気に入り</th>
            <td><%= render "favorites/favorite-btn", shop: shop %></td>
          </tr>
        </table>
      </div>
    <% end %>
  </div>
</div>