config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get   'inquiry'         => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'

  get "search" => "searches#search"

  devise_for :users

  root 'homes#top'
  get 'about' => 'homes#about'


  resources :shops, only: [:new,:index,:show,:edit,:create,:destroy,:update]do
    resource :favorites, only: [:create, :destroy]
    resources :shop_comments, only: [:create, :destroy]
  end

  resources :ranks, only: [:index]

  resources :users, only: [:index,:show,:edit,:update] do
    resources :favorites, only: [:index]
  end
  #退会確認画面
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  #論理削除用のルーティング
  patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'

  resources :notifications, only: [:index]


end

app/models/shop_comment.rb
class ShopComment < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  validates :comment, presence: true,length:{maximum:200}

end

app/controllers/shop_comments_controller.rb
class ShopCommentsController < ApplicationController

  def create
    @shop = Shop.find(params[:shop_id])
    @comment = current_user.shop_comments.new(shop_comment_params)
    @comment.shop_id = @shop.id
    if @comment.save
      #通知の作成
      @shop.create_notification_comment!(current_user, @comment.id)
    end
  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    ShopComment.find(params[:id]).destroy
  end

  private

  def shop_comment_params
    params.require(:shop_comment).permit(:comment)
  end

end

app/helpers/shop_comments_helper.rb
module ShopCommentsHelper
end

app/views/shop_comments/_index.html.erb
<% shop.shop_comments.each do |shop_comment| %>
  <tr>
    <td><%= link_to user_path(shop_comment.user) do %>
          <%= image_tag shop_comment.user.get_profile_image, size:"100x100" %></br>
          <%= shop_comment.user.nickname %>
        <% end %>
    </td>
    <td><%= shop_comment.comment %></td>
    <td>
      <% if shop_comment.user == current_user %>
        <%= link_to "destroy", shop_shop_comment_path(shop_comment.shop, shop_comment), method: :delete, remote: true, class: "btn btn-danger" %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/shop_comments/create.js.erb
$("#shop_<%= @shop.id %> .comments-count").html("コメント数: <%= @shop.shop_comments.count %>");
$(".shop_comments").html("<%= j(render 'shop_comments/index', shop: @shop) %>");
$("#shop_comment_comment").val("");

app/views/shop_comments/destroy.js.erb
$("#shop_<%= @shop.id %> .comments-count").html("コメント数: <%= @shop.shop_comments.count %>");
$(".shop_comments").html("<%= j(render 'shop_comments/index', shop: @shop) %>");
$("#shop_comment_comment").val("");